services:
  backend:
    container_name: backend
    build: ./backend/
    ports:
      - "8000:${APP__PORT}"
    environment:
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__HOST: database
      DB__PORT: 5432
      DB__NAME: ${DB__NAME}

      REDIS__HOST: redis
      REDIS__PORT: 6379
      REDIS__PASSWORD: ${REDIS__PASSWORD}
      
      JWT__ALGORITHM: ${JWT__ALGORITHM}
      JWT__SECRET_KEY: ${JWT__SECRET_KEY}
      JWT__ACCESS_EXPIRE_SECONDS: ${JWT__ACCESS_EXPIRE_SECONDS}
      JWT__REFRESH_EXPIRE_SECONDS: ${JWT__REFRESH_EXPIRE_SECONDS}

      APP__PORT: ${APP__PORT}
      APP__ENV: ${APP__ENV}
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  database:
    image: postgres:18-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d:ro
      - database_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --requirepass "${REDIS__PASSWORD}"
      --appendonly yes 
      --appendfsync everysec
    healthcheck:
      test: [ "CMD-SHELL", "REDISCLI_AUTH=${REDIS__PASSWORD} redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
      start_interval: 5s
    restart: unless-stopped

volumes:
  database_data:
  redis_data:
