services:
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.pnpm-store

    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json

        - action: rebuild
          path: ./frontend/package-lock.json

        - action: rebuild
          path: ./frontend/Dockerfile
