import { defineStore } from 'pinia'
import type { Task } from '@/types/tasks.ts'

const useTasksStore = defineStore('tasks', {
  state: () => ({
    // TODO: replace with API call
    tasks: [
      {
        id: 1,
        title: 'Орг. встреча волонтёров',
        description: 'Подготовить план мероприятия и список участников',
        deadline: '2026-06-25T18:00:00',
        points: 40,
        answer: '',
        status: 'available',
      },
      {
        id: 2,
        title: 'Фотоотчёт с акции',
        description: 'Загрузить фото и короткое описание прошедшей акции',
        deadline: '2026-06-28T23:59:00',
        points: 30,
        answer: '',
        status: 'available',
      },
      {
        id: 3,
        title: 'Анкета участника форума',
        description: 'Заполнить анкету для участия в молодёжном форуме',
        deadline: '2026-07-02T12:00:00',
        points: 20,
        answer: '',
        status: 'available',
      },
      {
        id: 4,
        title: 'Эссе о волонтёрстве',
        description: 'Написать эссе на 1-2 страницы о личном опыте волонтёрства',
        deadline: '2026-07-05T20:00:00',
        points: 50,
        answer: '',
        status: 'available',
      },
      {
        id: 5,
        title: 'Регистрация на слёт',
        description: 'Подать заявку на участие в летнем слёте движения',
        deadline: '2026-06-20T12:00:00',
        points: 15,
        answer: 'Заявка отправлена, жду подтверждения',
        status: 'submitted',
      },
      {
        id: 6,
        title: 'Отчёт по субботнику',
        description: 'Прислать отчёт о проведённом субботнике с фото',
        deadline: '2026-06-15T18:00:00',
        points: 25,
        answer: 'Отчёт во вложении, субботник прошёл успешно',
        status: 'submitted',
      },
      {
        id: 7,
        title: 'Мероприятие 1',
        description: 'Организация и проведение мероприятия для участников движения',
        deadline: '2024-02-15T10:00:00',
        points: 95,
        answer: 'Мероприятие проведено, отчёт приложен',
        status: 'graded',
        submitted_at: '2024-02-15T10:00:00',
      },
      {
        id: 8,
        title: 'Мероприятие 2',
        description: 'Помощь в организации второго мероприятия',
        deadline: '2024-02-22T14:30:00',
        points: 78,
        answer: 'Задача выполнена',
        status: 'graded',
        submitted_at: '2024-02-22T14:30:00',
      },
      {
        id: 9,
        title: 'Практическое задание',
        description: 'Выполнение практического задания по организации волонтёрства',
        deadline: '2024-03-05T09:15:00',
        points: 88,
        answer: 'Выполнено',
        status: 'graded',
        submitted_at: '2024-03-05T09:15:00',
      },
      {
        id: 10,
        title: 'Выступление',
        description: 'Подготовка и проведение выступления на форуме',
        deadline: '2024-03-18T11:00:00',
        points: 42,
        answer: 'Выступление прошло',
        status: 'graded',
        submitted_at: '2024-03-18T11:00:00',
      },
      {
        id: 11,
        title: 'Проведение мероприятия',
        description: 'Организация мероприятия для местного сообщества',
        deadline: '2024-04-01T16:00:00',
        points: 91,
        answer: 'Готово',
        status: 'graded',
        submitted_at: '2024-04-01T16:00:00',
      },
    ] as Task[],
  }),

  getters: {
    availableTasks: (state) => state.tasks.filter((t) => t.status === 'available'),
    pendingTasks: (state) => state.tasks.filter((t) => t.status === 'submitted'),
    completedTasks: (state) => state.tasks.filter((t) => t.status === 'graded'),
  },
})

export { useTasksStore }